### PR TITLE
Mermaid JS integration + JSX in markdown

### PR DESCRIPTION
**Pull request by etimberg**
Work in progress support for Mermaid documents.

## Working Features
* All mermaid document types
* Custom width and height

## Not Working
* passing a custom config as described at the end of the documentation

FYI: contains changes from #35 ad #36 so the diff appears bigger than it really is.

### CODE REVIEW

**Comment by etimberg** [comment]
@zsherman I got the start of a JSX -> HAST convert step into the pipeline. Can you take a look at it and let me know if it's going in the direction you had in mind?

Stuff I know still needs to be done

* [ ] Refactor `toHast.js` into smaller modules
* [ ] Try and refactor the parser to use `acorn.parse` instead of the weird regexp stuff that is there now
* [ ] Add tests for JSX parser with literal props (string, number, object)
* [ ] Add tests for nested object props
* [ ] Add tests for nested react elements
* [ ] Documentation on what JSX props are allowed (aka avoid expressions and stick to literals)

**Comment by zsherman** [comment]
@etimberg mind fixing the conflicts?

**Comment by etimberg** [comment]
Done

**Comment by etimberg** [comment]
@zsherman is this good to merge?

**Pull request merged**
